project:
  type: website

website:
  title: "CH4004-R.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - intro.qmd
      
filters:
  - live

webr:
  packages:
    - base
    - gradethis
    - tidyverse

format:
  live-html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

engine: knitr

editor: visual

