project:
  type: website

website:
  title: "CH4004 R programming"
  page-navigation: true
  navbar:
    logo: CH4004-R-logo2.png
    left:
      - href: index.qmd
        text: Home
      - Workshop1.qmd
      - Workshop2.qmd
      - href: Workshop3_introduction.qmd
        text: Workshop 3
      - href: Workshop4_introduction.qmd
        text: Workshop 4
      - href: Workshop5_introduction.qmd
        text: Workshop 5
      - href: Workshop6_introduction.qmd
        text: Workshop 6
  
  sidebar:
    style: "docked"
    search: true
    contents: 
      - Workshop1.qmd
      - Workshop2.qmd
      - section: "Workshop 3"
        contents: 
          - Workshop3_introduction.qmd
          - Workshop3_ggplot.qmd
          - Workshop3_plot-types.qmd
          - Workshop3_ggplot-themes.qmd      
      - section: "Workshop 4"
        contents: 
          - Workshop4_introduction.qmd
          - Workshop4_Rscript0.qmd
          - Workshop4_Rscript1.qmd
          - Workshop4_Rscript2.qmd
      - section: "Workshop 5"
        contents: 
          - Workshop5_introduction.qmd
          - Workshop5_exploring-data.qmd
          - Workshop5_correlating-data.qmd
          - Workshop5_linear-regression.qmd
          - Workshop5_limits.qmd
      - section: "Workshop 6"
        contents: 
          - Workshop6_introduction.qmd
          - Workshop6_exploring-data.qmd
          - Workshop6_t-tests.qmd      
          - Workshop6_ANOVA.qmd 
          
filters:
  - tools_tabset.lua

resources:
  - data

webr:
  packages:
    - base
    - gradethis
    - tidyverse
    - ggplot2

format:
  live-html:
      css: styles.css
      theme:
      - cosmo
      - brand
  

engine: knitr
