project:
  type: website

website:
  title: "CH4004 R programming"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Workshop1.qmd
      - Workshop2.qmd
      
filters:
  - live

resources:
  - data

webr:
  packages:
    - base
    - gradethis
    - tidyverse
    - ggplot2

format:
  live-html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

engine: knitr

editor: visual

